<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$helper = $this->helper(\Armanet\Integration\Helper\Data::class);
$isTrackingEnabled = $helper->isTrackingEnabled();

if ($isTrackingEnabled) {
    $scriptContent = "
        require(['armanet_cart_listener'], function(cartListener) {
            cartListener();
        });
    ";

    echo $secureRenderer->renderTag('script', [], $scriptContent, false);
}
