<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$helper = $this->helper(\Armanet\Integration\Helper\Data::class);

if ($helper->isTrackingEnabled() && !$helper->isCurrentUserExcluded()) {
    $debug = $helper->isDebugEnabled() ? 'true' : 'false';

    $scriptContent = "
        require(['armanet_cart_listener'], function(cartListener) {
            cartListener({debug: {$debug}});
        });
    ";

    echo $secureRenderer->renderTag('script', [], $scriptContent, false);
}
